FROM python:3.7.1-slim-stretch

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY *-requires.txt ./
RUN pip install --upgrade pip setuptools \
  && pip install --user --no-cache-dir --no-warn-script-location -r dev-requires.txt

ENV PYTHONUNBUFFERED 1
ENV PATH $PATH:/root/.local/bin
ENV FLASK_APP src/app.py
ENV FLASK_ENV development

COPY ./ ./

EXPOSE 5000

CMD python src/app.py
